// <auto-generated />
using System;
using Backend_Connection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_Connection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402164800_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_Connection.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdminPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RemovalReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemovedByAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("RemovedUserId")
                        .HasColumnType("int");

                    b.Property<string>("RemovedUserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SystemBookingCount")
                        .HasColumnType("int");

                    b.Property<int>("SystemRequestCount")
                        .HasColumnType("int");

                    b.Property<int>("SystemUserCount")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Backend_Connection.Models.Availability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<DateTime>("AvailableDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Availabilities");

                    b.HasData(
                        new
                        {
                            AvailabilityId = 1,
                            AvailableDateTime = new DateTime(2026, 4, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            IsTaken = false
                        },
                        new
                        {
                            AvailabilityId = 2,
                            AvailableDateTime = new DateTime(2026, 4, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            IsTaken = false
                        },
                        new
                        {
                            AvailabilityId = 3,
                            AvailableDateTime = new DateTime(2026, 4, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            IsTaken = false
                        });
                });

            modelBuilder.Entity("Backend_Connection.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LessonDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("LessonTime")
                        .HasColumnType("time");

                    b.Property<string>("LessonType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            BookingStatus = "Confirmed",
                            CreatedAt = new DateTime(2026, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            LearnerId = 1,
                            LessonDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LessonTime = new TimeSpan(0, 10, 0, 0, 0),
                            LessonType = "Beginners",
                            UpdatedAt = new DateTime(2026, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Backend_Connection.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("InstructorCarType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstructorPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            InstructorCarType = "Manual",
                            InstructorCode = "INS001",
                            InstructorEmail = "abraham.smith@example.com",
                            InstructorName = "Abraham Smith",
                            InstructorPasswordHash = "hash1",
                            InstructorPhone = "07123456789",
                            InstructorStatus = "Active"
                        },
                        new
                        {
                            InstructorId = 2,
                            InstructorCarType = "Automatic",
                            InstructorCode = "INS002",
                            InstructorEmail = "ali.john@example.com",
                            InstructorName = "Ali John",
                            InstructorPasswordHash = "hash2",
                            InstructorPhone = "07987654321",
                            InstructorStatus = "Active"
                        });
                });

            modelBuilder.Entity("Backend_Connection.Models.Learner", b =>
                {
                    b.Property<int>("LearnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerId"));

                    b.Property<string>("LearnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearnerLicenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LearnerPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearnerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearnerStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NextLessonCount")
                        .HasColumnType("int");

                    b.Property<int>("PastLessonCount")
                        .HasColumnType("int");

                    b.HasKey("LearnerId");

                    b.ToTable("Learners");

                    b.HasData(
                        new
                        {
                            LearnerId = 1,
                            LearnerEmail = "adam.lee@example.com",
                            LearnerLicenceId = "L1234567",
                            LearnerName = "Adam Lee",
                            LearnerPasswordHash = "hash3",
                            LearnerPhone = "07111111111",
                            LearnerStatus = "Active",
                            NextLessonCount = 1,
                            PastLessonCount = 0
                        },
                        new
                        {
                            LearnerId = 2,
                            LearnerEmail = "maria.khan@example.com",
                            LearnerLicenceId = "L7654321",
                            LearnerName = "Maria Khan",
                            LearnerPasswordHash = "hash4",
                            LearnerPhone = "07222222222",
                            LearnerStatus = "Active",
                            NextLessonCount = 0,
                            PastLessonCount = 2
                        });
                });

            modelBuilder.Entity("Backend_Connection.Models.LessonOutcome", b =>
                {
                    b.Property<int>("OutcomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutcomeId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("LessonNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonOutcomeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LessonRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("NotesCreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OutcomeId");

                    b.HasIndex("BookingId");

                    b.HasIndex("InstructorId");

                    b.ToTable("LessonOutcomes");
                });

            modelBuilder.Entity("Backend_Connection.Models.StudentRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AcceptanceMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemovalReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("LearnerId");

                    b.ToTable("StudentRequests");
                });

            modelBuilder.Entity("Backend_Connection.Models.Availability", b =>
                {
                    b.HasOne("Backend_Connection.Models.Instructor", "Instructor")
                        .WithMany("DbAvailabilities")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Backend_Connection.Models.Booking", b =>
                {
                    b.HasOne("Backend_Connection.Models.Instructor", "Instructor")
                        .WithMany("DbBookings")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_Connection.Models.Learner", "Learner")
                        .WithMany("DbBookings")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("Backend_Connection.Models.LessonOutcome", b =>
                {
                    b.HasOne("Backend_Connection.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_Connection.Models.Instructor", null)
                        .WithMany("InstructorOutcomes")
                        .HasForeignKey("InstructorId");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Backend_Connection.Models.StudentRequest", b =>
                {
                    b.HasOne("Backend_Connection.Models.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Backend_Connection.Models.Instructor", "Instructor")
                        .WithMany("IncomingRequests")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Backend_Connection.Models.Learner", "Learner")
                        .WithMany("StudentRequests")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("Instructor");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("Backend_Connection.Models.Instructor", b =>
                {
                    b.Navigation("DbAvailabilities");

                    b.Navigation("DbBookings");

                    b.Navigation("IncomingRequests");

                    b.Navigation("InstructorOutcomes");
                });

            modelBuilder.Entity("Backend_Connection.Models.Learner", b =>
                {
                    b.Navigation("DbBookings");

                    b.Navigation("StudentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
